### ISSUE TITLE
Add cmd+i and cmd+b for Mac users

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1148]
If possible to update the editor to allow the use of common keyboard hotkeys to make formatting text faster, that would be awesome.  Examples would be `ctrl/cmd + i `and `ctrl/cmd + b` to italicize and bold, respectively.  And/Or something like the FancyPants editor on Reddit.

Just throwing feature requests out there to see what sticks!

**Comment by calculuschild** [comment]
Currently I believe ctrl I and ctrl b already insert asterisks in the position. Is this not working for you?

Keep the suggestions coming though! It's all good!

**Comment by ericscheid** [comment]
The editor pane does already have keyboard shortcuts for bold and italics .. are these not working for you?

**Comment by Gazook89** [comment]
Ah, ctrl does indeed work.  However, on a Mac, that isn't "right".  Control works, but for most using a Mac the expectation would be that Command would do the trick instead.  Perhaps if both were functional?

Also, this seems to be a one-way thing.  It's not possible to un-asterisk bold or italics using the same hotkeys.  It just doubles up.

**Comment by calculuschild** [comment]
Ah I see. In that case, we can try to make both key combos work. That shouldn't be too hard.

There also might be a way to undo italics, but I can see that getting complicated.

For instance if you have this text and your cursor is at the X:

`This sentence *has somXe italics and **bold**** inside!`

What happens when you hit ctrl-i? Does the word "some" get asterisks around it?   Does a new set of asterisks appear in the middle of "some"? Do the outermost asterisks disappear? Not only do you have to parse all the nearby text for italics/not italics, but you have to count numbers of asterisks to make sure you don't mess up the bold on "bold". And that problem is a nightmare. Maybe possible, but probably rough. :/

**Comment by Gazook89** [comment]
Why not just add the asterisks where the highlight/selection starts and ends? If nothing is selected, including when the cursor is just inside a word, nothing happens. 

It should be relatively intuitive that the set of asterisks you need (depending on whether you choose italic or bold) appear at the start or end of a selection, even if it sort goofs up the format around other asterisks. 

In your example, nothing would happen, since the cursor hasn't highlighted anything. If you highlighted the word Some, and hit ctrl I, a set of single asterisks get added to either side of Some and it no longer becomes italicized, but leaves the rest italicized.

**Comment by calculuschild** [comment]
So here's where we are at now:

> Why not just add the asterisks where the highlight/selection starts and ends? 

So currently, ctrl-i does just that. It creates asterisks surrounding the current selected text.

Now since the original designer hadn't thought about the case where *nothing* is selected, ctrl-i weirdly inserted `|**` where `|` is the cursor position in that case. Ctrl-B resulted in `|****`. Pull Request #1078 fixed this "no selection" case so that the asterisks appear around the cursor you you can just start typing words, due to popular request. And it is a nice feature to be able to start typing in italics or bold without having to grab the mouse and drag over the words you want to modify.

I think this combination is pretty reasonable, and removing the no-select option after we so recently added it I think is going to confuse people. :/ I also like that it follows the other "snippet" behavior of inserting new code, where trying to "remove" a feature just requires extra logic.

> If you highlighted the word Some, and hit ctrl I, a set of single asterisks get added to either side of Some and it no longer becomes italicized, but leaves the rest italicized.

This sounds simple in principle, but in reality it wouldn't work quite that easily. With the update to the markdown parser that will be part of v3, spacing for the asterisks becomes more strict. For example: `This is **bold**` works fine, but `This is ** bold **` will not because spaces are not allowed directly before or after the asterisks. So then, if you want to "unbold" a selection by putting asterisks around it, you really have to know if the region is already bolded, and if not, place the asterisks like so: `other words **selection** other words`, but if the region *is* bolded, the spacing needs to go like this `other words** selection **other words`. If you have selected only part of a word, it gets even more convoluted. I should know, because I [rewrote the italics/bold detection for Marked.js](https://github.com/markedjs/marked/pull/1686) to better follow the Markdown specifications just for the Hombrewery, because people were getting all sorts of broken code to do things. Ugh...

Maybe as a future thing though. I'm not putting it completely off the table. Just not a priority for now. If you want to try your hand at a PR I'm all for it!

**Comment by RKuerten** [comment]
I created a quick fiddle where the Ctrl+B/I shortcuts have the functionality of both adding and removing bold/italic if they are in the outmost part of the selection, but with Italics using `_` instead of `*`. I can create a PR for it later.

[You can check it here](https://jsfiddle.net/RodrigoKuerten/mdup4n8f/45/). There's also code for ~~strikethrough~~ biddings, but there's probably a better shortcut for it. 

About Cmd key biddings, I can't help as I don't have a Mac.

**Comment by calculuschild** [comment]
This has been fixed with #1191
