### ISSUE TITLE
Can't delete Google Brews from the Metadata Editor panel

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1196]
Looks like that button is sending the wrong file id to Google. Deleting from the User page works fine, so we just need to make sure this button is sending the correct value to the API. The confirmation dialog boxes do pop up and the page does jump to the home page as normal though so all the other steps in the process are working.

![image](https://user-images.githubusercontent.com/5878534/105094056-ae7a7f80-5a71-11eb-954c-fecca1b5a10a.png)

**Comment by G-Ambatte** [comment]
I'm at work at the moment so I've only had a quick glance at this, but it appears that the delete from the Metadata editor is handled in lines 54-58 of `homebrewery/client/homebrew/editor/metadataEditor/metadataEditor.jsx` which I've reproduced here:

request.delete(`/api/${this.props.metadata.editId}`)
			.send()
			.end(function(err, res){
				window.location.href = '/';
			});

However the function to delete a brew from the user page includes these lines (32-44) in `homebrewery/client/homebrew/pages/userPage/brewItem/brewItem.jsx`:

		if(this.props.brew.googleId) {
			request.get(`/api/removeGoogle/${this.props.brew.googleId}${this.props.brew.editId}`)
				.send()
				.end(function(err, res){
					location.reload();
				});
		} else {
			request.delete(`/api/${this.props.brew.editId}`)
				.send()
				.end(function(err, res){
					location.reload();
				});
		}

So it appears that the Metadata Editor's Delete Brew link was never updated to detect brews stored on Google. It might be as simple as copying the extra lines of code across, although in order to maximise code re-use and prevent this from happening again, it might be worthwhile to instead link the Metadata Editor's delete function to the existing BrewItem delete functionality so that any future changes are automatically reflected in both places.
