### ISSUE TITLE
Systems are not removed from database

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1221]
## Issue

It appears that when the `systems` array is written to the database, items that are in positions greater than the current length of the `systems` array are not removed.

---

### Reproduction Steps:

1. Tag a brew with all four of the systems in the Metadata Editor tab.
2. Save the brew.
3. Return to the Metadata Editor and untick the Pathfinder systems box
4. Save the brew.
5. Refresh the page.
6. Check the Metadata Editor - Pathfinder has returned.

---

### Second Repro:

1. Tag a brew with one or more systems.
2. Save.
3. Untick all systems boxes.
4. Save.
5. Refresh.
6. All ticks have returned.

---

### Third Repro:

1. Tag a brew with any two non-5e systems.
2. Save.
3. Tick 5e.
4. Save.
3. Untick one non-5e system.
4. Save.
5. Untick the other non-5e system.
6. Save.
7. Refresh - 5e is the only remaining system, but cannot be removed. Checking this brew in the database will show that '5e' is in all positions 0-2 in the `systems` array.

![Example image](https://user-images.githubusercontent.com/19826659/106108698-7e3b8b00-61ad-11eb-974e-b9c9875e83bf.png)

**Comment by ericscheid** [comment]
The bug is here:
https://github.com/naturalcrit/homebrewery/blob/d15bec08a3cb1c80fdb34a28f2bf50f50112a597/server/homebrew.api.js#L55

`_.merge({arr:[1,2,3]}, {arr:[5,6]})` produces `{arr: [5, 6, 3]}` .. i.e. _.merge recursively merges objects and elements, so `target.arr[0]` is replaced with `source.arr[0]` (etc).

Thus:
`_.merge({systems:[5e,4e,3.5e,PF]}, {systems:[4e,3.5e,PF]})` produces `{systems:[4e,3.5e,PF,PF]}`.


Additionally, this: https://github.com/naturalcrit/homebrewery/blob/d15bec08a3cb1c80fdb34a28f2bf50f50112a597/client/homebrew/editor/metadataEditor/metadataEditor.jsx#L32-L39 
wasn't written with the possibility that the system being pushed into the array is already in the array, and so by particular sequences of updates, saves, and reloads we end up with `systems:["5e","4e","3.5e","3.5e","4e","4e","4e"]`.

**Comment by ericscheid** [comment]
We can keep using `_.merge()` (to handle future fields, generally)m but line 55 in _homebrew.api.jsx_ does need to change.

Either 
1. save the pre-merge `brew` and after `_.merge` manually re-set `systems` (and also `authors` for the same reason, and also `views` because the browser shouldn't be setting the views count to whatever old value it got when the editpage was loaded); or
2. `_.merge(object, source, callback, thisArg)` is a thing and we can thus control which elements get merged, which get replaced, and which get ignored.

**Comment by calculuschild** [comment]
Lodash's [_.union](http://lodash.com/docs#union) looks like a good drop-in replacement.] for `_.merge` which I think will fix part of this.

**Comment by ericscheid** [comment]
1. `_.union` only works on arrays, not objects.
2. `_.union([5,3.5], [4])` ⇒ `[5,3.5,4]` .. which is the same as `_.merge`

`_.merge(object, source, callback, thisArg)` seems to be the way. The main problem with `_.merge` is it is a deep merge.

Wait ..
> _.merge(object, [sources])
This method is like _.assign except that it recursively merges [...]

Ah, `_.assign` is a shallow merge. Which is what we want.

```
var object = {
  'title': 'string',
  'systems': [3.5,4,5]
  };
 
var other = {
  'title': 'new string',
  'systems': [5]
  };
 
_.merge(object, other); // => {title: "new string", systems: [5, 4, 5]}
_.assign(object, other); // => {title: "new string", systems: [5]}
```

----

Except, separate from #1221, we still want to deep merge for `authors`, and to ignore `views` i.e. maintain the server value of `views`. Which are separate issues (not yet logged into github).

**Comment by 5e-Cleric** [comment]
Just tested, this is no longer an issue, closing.
