### ISSUE TITLE
Download as .md file

### ISSUE THREAD

**Issue by SRugina** [naturalcrit/homebrewery#1284]
## Description

Currently, the download as text file downloads the brew as, well, a `.txt` file.

It would be preferable to download as a `.md` file (also set content type to `text/markdown` instead of `text/plain`) since, you know, the brew is written in markdown.

Should be a pretty small PR, shall I open one now, or are there larger PRs I should wait for before opening this one?

**Comment by calculuschild** [comment]
`.txt` makes it easy to open/edit for the average user since they can just double-click it and it works with Notepad or whatever when it comes time to copy/paste it into the website. Once we start throwing on other file extensions, users start getting really confused when you click it and nothing happens, or your computer starts asking you what program to open it with.... I'm open to discussing further but my initial response is this might confuse people more than it helps.

**Comment by SRugina** [comment]
Ah yes, that's a valid concern I completely overlooked! I'd forgotten that by default most systems don't open `.md` files.

**Comment by BrandonKMLee** [comment]
> I'd forgotten that by default most systems don't open .md files

So Marktext or Joplin?
