### ISSUE TITLE
PDFs have duplicate image data

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1311]
Background images (parchment texture, text block borders, etc.) are fully duplicated for each occurrence in the resulting PDF. This results in large file sizes (and potentially browsers crashing) as pages increase.

I know PDFs can be made to re-use image data multiple times from the same resource, which unfortunately Chrome's print-to-pdf doesn't do. If there's an alternate PDF generator or post-processing step we could use to detect and remove identical image data that would be just nice to have. See #201

**Comment by ericscheid** [comment]
This might not be a Chrome thing but rather a system/OS thing (i.e. chrome might well be handing off to the OS to create the PDF). That seems to be the thing happening with MacOS. And thus different results for different users.

That said, I do wonder if declaring the images via base64 inlines (and not via a distinct resource URI) is causing this duplication.

We should look to figuring out how to generate the PDF on the server and sending that as the response to a resource request of the form `https://homebrewery.naturalcrit.com/pdf/:id`

That is, leave the `/print/:id` route as is [for backwards compatibility and 3rd party links] but change the ![Get PDF](https://user-images.githubusercontent.com/2605467/113819387-92f35b00-97bc-11eb-82b0-2b13a82243f9.png) menu-bar link to `/pdf/:id` — it'll also help with related PEBKAC support issues too)

**Comment by G-Ambatte** [comment]
> We should look to figuring out how to generate the PDF on the server and sending that as the response to a resource request of the form https://homebrewery.naturalcrit.com/pdf/:id

A user was asking about PanDoc compatibility in the sub-reddit recently. I looked at it (very) briefly; it can convert Markdown to PDF via LaTeX (see example 13 [here](https://pandoc.org/demos.html)). Custom formats can be written in Lua, if the HB Markdown is not sufficiently close to the existing Markdown formats.

Just to be clear: I'm absolutely behind shifting to producing the PDFs in-house, as it were, rather than relying on the user's ability to Print to PDF. It will be a big move though, as there are bound to be billions of tiny bugs where the Chrome webpage does not exactly match the rendered PDF file.  
However, I suspect that it's probably big enough to need not just it's own separate issue, but probably an `EPIC` tag to go with it.

**Comment by G-Ambatte** [comment]
The other side of the PanDoc conversation is that it feels an awful lot like using a sledgehammer to crack a single nut - Homebrewery doesn't *need* all of the bells and whistles PanDoc provides.

**Comment by calculuschild** [comment]
Here's the Chrome issue for this for future reference. Give it a star to bring more attention!

https://bugs.chromium.org/p/chromium/issues/detail?id=1196526&q=background-image%20pdf&can=2

**Comment by dbolack-ab** [comment]
Given that this is a Chrome bug, do we need to keep this open?

**Comment by calculuschild** [comment]
Added this to the larger Chrome Bugs issue. Can close this now.
