### ISSUE TITLE
Split panel resize broken when viewing Metadata tab

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1388]
If you try to resize the left pane while displaying the Metadata tab, the cursor will be locked into resize mode until you refresh or close the page.

**Comment by ericscheid** [comment]
When end-dragging in problem mode this is what appears in console:

![cannot read property updateSize of undefined](https://user-images.githubusercontent.com/2605467/127675966-2e0a4178-07c1-4e56-9d96-3d6ee9386485.png)

I also have a sneaky suspicion this has something to do with how the three modes are built — previously the metaDataEditor was a panel that overlaid the code editor, but now it completely replaces the code editor.

When the three mode buttons are clicked, the `<div class="editor" />` element gets ripped out and replaced. When the Properties Editor button is clicked then that `<div/>` contains `<div class="metaDataEditor" />` (instead of `<div class="codeEditor" />`. So .. the code that eventually instantiates metaDataEditor probably isn't setting up props correctly, eventually causing the "cannot read property updateSize of undefined" exception when end-dragging.

![metadataeditor mode](https://user-images.githubusercontent.com/2605467/127677049-87d95327-b23c-4783-86e3-6dd58832624c.png)

**Comment by calculuschild** [comment]
`this.refs.codeEditor?.updateSize();`

A one-character fix.

**Comment by calculuschild** [comment]
Fixed by https://github.com/naturalcrit/homebrewery/commit/213ef9d94b625b05e4fb6192122c2deb30c4ec01
