### ISSUE TITLE
Wide div directly after text with manual column-break drops to bottom of page

### ISSUE THREAD

**Issue by uruzrune** [naturalcrit/homebrewery#144]
**Browser Type/Version**: Chrome 51.0.2704.103 m (64-bit)

**Operating System**: Windows 10

**Issue Description**: PDF Print looks wonky when a wide table is used. It looks like the table is being shifted to the bottom of the page for whatever reason. Looks fine in the editor.

**Brew code to reproduce**:

```
http://homebrewery.naturalcrit.com/edit/rkxcUKqOr (Feel free to trash/modify this as it's a c/p from my regular document) Looks fine in the editor, but PDF print results in a huge gap. See image attached below.
```

**Related Images** : http://imgur.com/fnG2afp

**Comment by stolksdorf** [comment]
No idea what could be causing this. Looks like an issue with Chrome.

**Comment by Tsurumah** [comment]
Have you tried removing the text from above the table and seeing if it renders correctly?

**Comment by uruzrune** [comment]
Removing the two columns above allows the table to render correctly for printing, yes. But that defeats the "layout" purpose of breaking up the columns with a table.

**Comment by phaeren12** [comment]
@stolksdorf 
> No idea what could be causing this. Looks like an issue with Chrome.

It's not just Chrome, tried using Firefox to correct the issue and the layout gets even more messed up.

> Have you tried removing the text from above the table and seeing if it renders correctly?

Have to agree with @uruzrune, removing the text above would defeat the purpose.

**Comment by tarper24** [comment]
This appears to be cause by the column break, and I'll tell you exactly why at the end of this post. However, the easiest fix for this is to make it's position absolute:

```HTML
<div class='classTable wide' style='position:absolute;top:380px;margin-right:64.252px;'>
```

This places it at the correct position in the render, and it also allows it to print properly. Hope that helped! For anyone else wandering onto this issue looking for a workaround: `margin-right` is to set it's right side in to the proper position. `top:380px;` is what you'll want to modify to match your needs. This may take some guess-and-check to get it right, but I got lucky that it was a multiple of ten on this one to get it in the right place. You may also decide you don't need it to be exact, and that is fine. It's your brew, after all!

Onto why this is happening: It seems like the wide table aligns to the bottom of the text that it is placed below from both columns, left and right. Since their is a column break (and if I recall correctly), the column break doesn't start the text in the next column, it uses whitespace to move the text onto the next column. Since the table looks for the lowest point of both columns, this causes it to place the top of the table at the bottom of the first column. Hope this helps you fix the problem in the code, if possible @stolksdorf.

print(closing);
print("~tarper24");

**Comment by quadz08** [comment]
I am having this issue with a PDF I am using as well. I've tried using the fix outlined by @tarper24, but it is throwing another issue - the table is no longer a Wide table, despite still using the classTable Wide class.

Here is a throwaway featuring the page at issue:
http://homebrewery.naturalcrit.com/edit/HJenIfvo2

**Comment by stolksdorf** [comment]
@quadz08 `position:absolute` and Css columns don't work together. Either remove the absolute position, or manually set your width.

**Comment by quadz08** [comment]
How can I manually set my width?

**Comment by stolksdorf** [comment]
`width:100%;` 

I personally would try and avoid messing with HTML + CSS as much as you can with Homebrewery, if you aren't familiar with it.

**Comment by quadz08** [comment]
Yeah I'm not trying to do anything fancy - I just need to be able to fix this one thing so I can print it to PDF properly. Thanks for your help. :)

**Comment by phaeren12** [comment]
@tarper24 

> This appears to be cause by the column break, and I'll tell you exactly why at the end of this post. However, the easiest fix for this is to make it's position absolute: `<div` class='classTable wide' style='position:absolute;top:380px;margin-right:64.252px;'>

Could you tell me where exactly to put this? Because when I add it, it does make the table absolute. But everything after the table becomes a smooshed indecipherable mess rendered just below the table and the file size goes from 5 pages to 2?

**Comment by tarper24** [comment]
You would need to change the current wide class table's `<div>` tag from `<div class='classTable wide'>` to `<div class='classTable wide' style='position:absolute;top:380px;margin-right:64.252px;'>` Just remember to change the `380` where it says `top:380px;` to however far down you need it to move. It will likely take some guess and check, but if you want it to look nice, it's worth it!

print(closing);
print("~tarper24");

**Comment by phaeren12** [comment]
@tarper24 
Is there a way to do this with the wide monster stat block too? Because that has the same problem and I can't seem to figure out how to use this to fix it...

**Comment by tarper24** [comment]
There a little bit trickier because they use markdown, however, not impossible. If you look at http://homebrewery.naturalcrit.com/edit/r1g8nZdLJe on the first page, it is a normal Wide Monster Stat Block, and on the second page, it is one with an absolute position. For the second one, you'll want to remove the two sets of underscores at the beginning: 
```
___
___
```
and replace it with `<hr><hr><blockquote style='position:absolute;top:380px;margin-right:64.252px;'>`, and don't forget to change the 380 to whatever you need it to be. Note: It must all be on the same line, otherwise it does not work. Also, you'll need to remove all of the `>` before every line in the stat block. Then just remember to place `</blockquote>` at the end of all of it.

~tarper24

**Comment by KindredWolf78** [comment]
I tried the workaround from tarper24 and it still does the same thing.  Page 3 of my document.

https://homebrewery.naturalcrit.com/share/BkPuppetf

**Comment by calculuschild** [comment]
Link to a current brew demonstrating this issue: https://homebrewery.naturalcrit.com/share/1rWh_ORYfwLdFGZszOOX-Oyw60-8cBny2zwT7v4sZOonV

**Comment by ericscheid** [comment]
Remove the `column-break` and let the browser balance the columns properly.

https://homebrewery.naturalcrit.com/share/P38MUp79Ps5N

**Comment by ericscheid** [comment]
A possible fix has been found https://stackoverflow.com/a/64611827/1601921 - needs coding, needs testing.

**Comment by calculuschild** [comment]
Worthy solution here:

https://homebrewery.naturalcrit.com/share/gfZg8oaQRC8w
