### ISSUE TITLE
If a snippet included a 'content' portion and 'style' portion...

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1440]
I am working on Cover Pages, and thought about how I would integrate with snippets.  The current cover page snippet just inserts markdown and then uses the default phb stylesheet, so the snippet is just inserted in the brew editor.  But if a cover page snippet was made for an alternate theme and thus needed additional css styling, it would mean either:

- inserting into the brew editor both the markdown and the styling together, where the cursor is currently
- inserting them markdown in the brew editor and the css into the style editor, but somehow determining where both would be inserted since the cursor can't be two places at once.

One idea I had was to transition snippets to a more 'library' like entity, rather than 'click and insert'.   Snippets could still be found in drop down menus but when clicked on, they would open a dialog box with the code snippet displayed and ready to be copy/pasted into the brew.   This would allow displaying both a markdown component and a css component in the same dialog box, but separated and ready for the user to copy each into the appropriate window, where they want them.

**Comment by calculuschild** [comment]
Snippets should only need to be Markdown. The associated styles for the snippets would already be in the CSS file for the theme that the user has loaded. If you want to make a new theme then that should go in an official CSS file that we add to the site and the user can swap between through a menu (do I want a PHB style or DMG style or something else?) Then in the future, we will add the ability to select an existing brew's style panel to use as the base style sheet rather than having to choose an official one.

I already have it working so we can swap out different theme CSS files (from phb to phb3 currently, but we want to add more). I just need to create the menu button.

Once those are working, I can take a look at adding custom snippets depending on what Theme the user has currently selected, but again, those should still just be Markdown and the styles will be in the theme's CSS file.

**Comment by calculuschild** [comment]
If you are creating a cover page to add to the official PHB style, I will update the snippet Markdown to use your syntax, and we will add the necessary CSS directly into the PHB.less file.
