### ISSUE TITLE
curly-injectors to target parent "page" element if no preceding sibling target

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1489]
If the `{curly-injector}` appears as the first chunk on a page (i.e. very beginning of brew, or following a `\page`) then have the values injected into the enclosing `<div class="page V3">` element.

That is, instead of defaulting to treating the `{curly-injector}` as plain text.

----
#### Example: adding a class to a page:

```
\page
{songsheet}
Non, rien de rien
Non, je ne regrette rien
Ni le bien, qu'on m'a fait
Ni le mal, tout ça m'est bien égal
```
Note that the usual classes of "page" and "V3" should be retained, even in face of `{class="overwrite"}`.

----

#### Example: adding a `lang` attribute to a page:

```
\page
{lang=fr}
Non, rien de rien
Non, je ne regrette rien
Ni le bien, qu'on m'a fait
Ni le mal, tout ça m'est bien égal
```

(note that adding a `lang` attribute to the whole brew is a separate issue #1343, and separately needed.)
(note 2: here we are injecting a html-attribute, not a style class or style rule. See #1489 for that.)

An attempt to override the `id` of a `<div class="page" id="p123">` should be ignored.

**Comment by ericscheid** [comment]
See also #1488

**Comment by jeddai** [comment]
If we set it up where it could be anywhere in the page like the pageNumber syntax, something like `{{page.class}}`, I think that would be better than specifically right after `\page`.

**Comment by calculuschild** [comment]
Right after `\page` seems more logical syntax to me. Injector curlies already can be used to target the immediately-preceding element. This expands the syntax to apply to the immediate parent if there is nothing preceding. This could apply to other nesting structures, for instance table cells? Divs?

```
|  header |  header |
|:-------:|:-------:|
|{blue} hi| not blue|

{{A div
{blue}
content?
}}

```

Not that we want to implement any of those necessarily.

But my main concern is so far none of our other syntax uses "keywords" to trigger something except for `\page` and `\column`, and I'm hoping we can keep those special cases to a minimum. The pagenumber syntax uses `pageNumber` as a CSS class, but not a functional keyword, if that makes sense. It can be placed anywhere because it's a standard DIV with an absolute position, so it doesn't matter where in the markdown it goes.

That's my 2 cents.

**Comment by Gazook89** [comment]
>This expands the syntax to apply to the immediate parent if there is nothing preceding.

As noted in the gitter, I'm not sure this would work any longer for targeting `.page` because now we have the `.columnWrapper` element which sits between the page and the content.  Or at least, that extra layer would need to be considered and accounted for and likely add some complexity we don't need?

With the recent introduction of the `:has()` pseudo-selector to Chrome (*and the hopeful implementation/release by FF*), I'm sort of swinging back to @jeddai's proposal of just inserting a "named span" onto a page and targeting that with `:has`.

Example brew:
```
{{cover-page}}

My Title

Subtitle

\page
{{credits-page}}

...

```

And then using `:has(.cover-page)` to give the cover page styling.

This would make it simple to insert snippets from the menus (possibly a new Page Layout menu).  Snippets could be `{{cover-page}}` or `{{layout,cover}}` or ....

**Comment by Gazook89** [comment]
Closing this per above.  It can be re-opened if we really still need to be able to inject into parent elements directly.
