### ISSUE TITLE
Created and Updated Dates not correct

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1506]
I mentioned it briefly in gitter, but figured an issue should be opened:  Last Updated and Created Date fields on the user page are not correct.  At least on Google linked brews.  If needed I can find out when some of these were *actually* created by finding my old reddit posts, but some are at least 6 months old, and then others were made this week....with many inbetween which are found elsehwere in the list.  And some of these I haven't opened in a long time.

Edit: and I don't think this is a "new" issue, but likely ties into the Google integration.  I've long noticed it, but didn't care because it was irrelevant information to me...now with sorting, it's actually a "problem".

<img width="844" alt="image" src="https://user-images.githubusercontent.com/58999374/127918970-5459ead5-eb88-44b0-b82e-84b94e1f5eec.png">

**Comment by G-Ambatte** [comment]
I think that perhaps the date information is being handled inconsistently between MongoDB and G-Drive; however if we push the data through the `Moment` module in the ordering function, it should handle the conversion correctly and then the data will be correctly ordered.

**Comment by G-Ambatte** [comment]
I've just found an issue with retrieving the creation date on Google brews; I'll untangle it from my current branch and submit as a separate PR.

**Comment by calculuschild** [comment]
There is a separate issue going on here as well. When we update the "views" count from visiting the share page, Google Drive will also update the modified time. HB does not do this because we specifically avoid MongoDB's "markModified" flag in those cases.

We will need to have some workaround for Google drive; we may be able to manually set the modified time.

https://developers.google.com/drive/api/v3/reference/files/update

https://stackoverflow.com/questions/12256055/keep-modified-time-of-file-upon-insert-into-google-drive-api-on-android?rq=1
