### ISSUE TITLE
Issue with `buildAll`

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1508]
Updating my FreeBSD install today to the latest version of Homebrewery, I encountered the following error during the `npm run postinstall` command (which is an alias for `npm run buildAll`):

```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received function render
    at writeFile (node:fs:1482:5)
    at go$writeFile (/usr/local/homebrewery/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/usr/local/homebrewery/node_modules/graceful-fs/graceful-fs.js:136:12)
    at /usr/local/homebrewery/node_modules/fs-extra/lib/output/index.js:18:27
    at /usr/local/homebrewery/node_modules/universalify/index.js:22:54 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

However, `npm run build` (which only runs `node scripts/buildHomebrew.js`) does not strike the error, so I assume it is occurring somewhere within `scripts/buildAdmin.js`.

Running in this state, the most noticeable issue so far is that the background color is incorrect, and as one would expect, none of the `/admin` routes return pages.
![image](https://user-images.githubusercontent.com/19826659/127947836-a5dc25ba-813c-48a5-ba7b-feed66a75aca.png)

**Comment by G-Ambatte** [comment]
Initial investigation indicates that it is probably related to having Node 15 installed, rather than 14.

**Comment by calculuschild** [comment]
I haven't updated the build script for Admin in a long, long time because I have never had occasion to use any of the admin pages.

I'm pretty sure it's this line here:
`	await fs.outputFile('./build/admin/bundle.css', await lessTransform.generate({ paths: './shared' }));`

With the newer version of Node, it doesn't like you passing in promises to that function (note how we are passing in an `await...` inside of another `await`.

The solution is to process the internal promise first, and only then pass it into `fs.outputFile`

```
	const css = await lessTransform.generate({ paths: './shared' });
	await fs.outputFile('./build/homebrew/bundle.css', css);
```

You can see this difference in the `buildHomebrew` script.

**Comment by G-Ambatte** [comment]
I'll give the a try once I get back to my PC. There's probably a larger question about what tools a Homebrewery admin requires, but I'll leave that as outside the scope of this issue.

**Comment by calculuschild** [comment]
I think Render.js is some optional thing from Vitreum I'd we wanted to make a static page or something. It's been a long time since I set up the buildhomebrew script so I can't remember. But it looks like we don't use it for anything on the homebrew side so it likely has no use in admin. Probably a leftover from the last time I updated and I just didn't finish updating the admin script.

**Comment by G-Ambatte** [comment]
I'll push a PR shortly with the `const css` and commenting out of the `render` line, which should close out this issue.
