### ISSUE TITLE
`{curly-injectors}` overwrite existing classes

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1536]
![image](https://user-images.githubusercontent.com/2605467/128691040-9edc6bb0-7e93-476d-bd4a-4b3c800ac9f3.png)

```
<style>
  .borders { border: 1px solid red;}
  .yellow {background-color: yellow;}
</style>

{{borders
This block has the `borders` class assigned.

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis.

}}

:::
{{borders
This block also has the `borders` class assigned.

Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. 

However, this post-fix `{curly-injector}` overwrites the class attribute entirely, including the HB class value of "block" which was inserted by the `{{curly-block-declaration`.
}}
{yellow}
```

This will break the views if #1489 implemented (i.e. the special class of `.page` will get whacked).

**Comment by ericscheid** [comment]
We can work-around #1489 as is an isolated special case.

This issue is similar to having multiple competing css-rules applying via the same selector, with just the most recent declaration taking effect. This is a user-authoring problem for the user-author to fix.

Closing.

**Comment by calculuschild** [comment]
This is working as intended; both curly divs/spans and curly injectors have the same behavior: overwrite any custom classes and inline styles with the contents of the curlies. There is no use case where a user should need to inject into a curly div instead of just adding the style directly into the div.

We just need to be clear what the expected behavior is.

> [bad syntax is on them]


*If* this becomes an issue in the future, we can change the behavior while V3 is still in "beta", but for now this is not a bug and is working as intended.
