### ISSUE TITLE
no save

### ISSUE THREAD

**Issue by LunchalotTwitch** [naturalcrit/homebrewery#1559]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by G-Ambatte** [comment]
This sounds like the Google credentials have expired, which happens one year after the last sign in via Google.

The fix for this is to head to https://www.naturalcrit.com/login and click logout if present (in small text at the bottom of the page), then click "Sign In with Google" which will refresh the Google credentials. If this was the source of the issue, it should now be resolved and it should not return for at least twelve months.

Logout location:
![image](https://user-images.githubusercontent.com/19826659/129470020-8a43b435-5189-46bc-8f66-a27b226c3b62.png)

---

If following these steps does not resolve the issue, please let us know!

**Comment by Gazook89** [comment]
closing as duplicate: #1580
