### ISSUE TITLE
Insert QR Code fails vs `/new` brew

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1710]
On the `/new` brew editor page, the *Insert QR Code* snippet inserts this:

    ![](https://api.qrserver.com/v1/create-qr-code/?
    data=https://homebrewery.naturalcrit.com/share/undefined
    &amp;size=100x100) {width:100px;mix-blend-mode:multiply}

Note the `undefined`. Entirely understandable how that happens .. but what do we do to fix?

Maybe detect the editor is on `/new` and a) use `SHARE-ID-HERE` instead of `undefined`, and maybe b) also insert `<!-- ATTENTION: You will need to insert your share id into the url above, once you do save this brew -->`.

**Comment by G-Ambatte** [comment]
Given that a new brew is only saved in local storage and can thus only be viewed on the device it was written on, the concept of sharing it via URL is fatally flawed.* However the simplest solution at this time is likely to pop an error/alert window consisting of "You cannot generate a QR code for an unsaved brew!"

---

\* - This may change in the future - for example, using the `/template` path (discussed elsewhere - #1538, for example) could allow someone to generate a specific brew entirely via a URL embedded in a QR code.

**Comment by calculuschild** [comment]
The qr code is not indented solely as a link to the current brew. It can be for anything. Link to a other website. Link to separate battlemap images. Link to a Patreon page. The snippet just uses the share link because it's a convenient url to show off what a QR code can do (and I think the original issue report was using it that way).

The *easiest* solution is to change the snippet to be a static address like just point to the Homebrewery home page.

The next easiest is to keep the current functionality, but if `shareid` doesn't exist, change the generated url.

I'm hesitant to add whole error popups and notifications and trying to tie that into the snippet system.

**Comment by G-Ambatte** [comment]
> The next easiest is to keep the current functionality, but if shareid doesn't exist, then fall back to a static url.

I like this one best.
