### ISSUE TITLE
Printing from /new is blank

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1789]
Reported from https://www.reddit.com/r/homebrewery/comments/ql2ai1/unsaved_brew_not_printing/

In a recent fix we allowed /print to use the `metadata` object to set the correct renderer. Turns out if the user has never altered the metadata from default, metadata is never saved to the localstorage and so the `/print` page crashes when it attempts to read the `renderer`  value here (`metaStorage` is null at this point):

https://github.com/naturalcrit/homebrewery/blob/09ca2a4fd96ac3fd5dfbb7efdc2aafad16e4e666/client/homebrew/pages/printPage/printPage.jsx#L47

Either we change that line to use optional chaining, or we ensure in `/new` that metadata is saved to localstorage when first loaded or something similar.

Easy fix either way.

**Comment by G-Ambatte** [comment]
Further to this, if the user clones a brew then attempts to print it without having altered it in any way, `/print` will instead load the contents of `localStorage` - we might need to trigger a save to `localStorage` on clicking the Get PDF button.

**Comment by calculuschild** [comment]
In that case the second option, saving to localstorage on print, makes more sense. Easy fix.

**Comment by G-Ambatte** [comment]
We should be able to convert the `<PrintLink>` nav item to a button that performs the save followed by the redirection.

---

A deeper cut would be to rebuild the `/print` system, instead passing the BrewRenderer output to the PrintPage as a prop, so that the current state of the editor content is always printed, rather than the most recent save. However, that is a much larger solution to this problem, and while possibly/probably beneficial in the long run, will not resolve this issue in a timely manner.

**Comment by calculuschild** [comment]
> A deeper cut would be to rebuild the /print system, instead passing the BrewRenderer output to the PrintPage as a prop, so that the current state of the editor content is always printed, rather than the most recent save. 

This could work but should only apply to the New page, not any edit or share pages since a user visiting the print page directly from a link would have no brewrenderer prop to pull from.

**Comment by ericscheid** [comment]
This problem has returned with some recent react-router changes.
