### ISSUE TITLE
Reverse-indent spell lists in stat block

### ISSUE THREAD

**Issue by Fralexion** [naturalcrit/homebrewery#182]
When listing a monster's spells, the formatting should be the way it is when starting a list right after a horizontal rule, where for each list item, the first line is not marked with a bulletpoint or indented, but all lines after that that aren't the start of a new list item are indented. 

Currently, making a list in a monster stat block when not immediately after a horizontal rule creates a list where all lines are indented the same amount, and each item starts with a bulletpoint symbol, partially cut off.

**Comment by The-Unapproachable** [comment]
I found that you can create MM-format lists within a monster stat block by using some Markdown.  To start the list, you create a new line by adding two spaces after the line of text and hitting return.  Then the list will start out without being indented.  Since spellcasting lists sometimes require two lines for each level, you can then double indent the second line to follow MM formatting.  To do this use "&nbsp;" <space> "&nbsp;" <space>.

**Comment by Gazook89** [comment]
Hanging indents are implemented in v3 using definition lists.

**Comment by calculuschild** [comment]
Added to the V3 changelog now. Closing.
