### ISSUE TITLE
Unexpected change in rendering in Google Chrome

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1828]
As reported on reddit, as of yesterday or today the rendering in brews has unexpectedly changed.  It seems to line up with the release of a new Chrome update, and is seen on GM Binder as well.  

[Reddit Post](https://old.reddit.com/r/homebrewery/comments/qv02dd/did_the_format_change_my_formatting_used_to_fit/) / [GM Binder Post](https://old.reddit.com/r/gmbinder/comments/qv5ple/is_there_less_room_to_put_the_texts_in_now/)

Per @calculuschild , it seems like maybe line-height is impacted?
> Edit: I can confirm this is tied to the recent Chrome update to v96 after testing before and after updating the browser. It looks like there may be multiple issues in this latest update related to some spacings being calculated in a slightly different way.
>
> It's hard to tell, but I think the main issue everyone is seeing here might be just the line-height being slightly taller than normal. I'll have to dig deeper though to be sure.
>
> Edit 2: The CSS values are all identical, but somehow the calculated total height of each element is 0.5-1.5 pixels taller for some reason, which is pushing the pages out of alignment. Still looking.

[Here are the Google Release notes.](https://chromium.googlesource.com/chromium/src/+log/95.0.4638.69..96.0.4664.45?pretty=fuller&n=10000)

1. [Change to computing fractional line-heights](https://chromium.googlesource.com/chromium/src/+/878d6b63935a792c8601ec401121dec4730ee4a2)

**Comment by Gazook89** [comment]
A temporary fix may be to change the `.phb p`/ `.page p` line height to 1.252em if using the standard font-size, rather than line-height 1.3em.  

On my machine, the *current* computed value of 1.3em is 15.5754px, and 1.252em is 15.0003px....so if this is related to line-heights now being floats rather than integers, it seems 1.252em is closer to the original.

I'm not sure if this plays out differently on other machines, though.  Also, if not wanting to impact Firefox, might consider creating a media query for browser and leave FF at 1.3em.  Of course, FF is 'not supported' and having split values between the browsers is a road to nightmaretown.

**Comment by calculuschild** [comment]
@Gazook89 Good find on the fractional line height change. That seems to be our best guess right now what happened. I suspect it isn't going to be changed back since they mention fractional line heights are more "correct" for calculating heights of boxes, etc. So unless we find anything different, we probably need to:

1) Change Legacy to use new line-height values to mimic the old values as you suggest

2) Change V3 in a similar way, but we don't need to feel restricted to "integer" pixel values. Instead let's make sure our measurements are "correct" according to the PHB, which is likely an even multiple of the font size (i.e., 1.25 em vs 1.252em). Apparently the sizes I picked were "rounded down" in the browser so they weren't accurate anyway.

On the plus side, this Chrome update might start to alleviate some of the "my brew looks different on different zoom levels/monitors" issues.

**Comment by calculuschild** [comment]
Just fiddling with Chrome 95, I'm seeing that a single-line paragraph seems to round it's height in units of 0.8px.

`line-height` | actual height
--------------|---------------
16.0 px         | 16.0px
16.7 px         | 16.0px
16.8 px         | 16.8px
16.9 px         | 16.8px
17.0 px         | 16.8px
17.4 px         | 16.8px
17.6 px         | 17.6px
18.0 px         | 17.6px

**Comment by calculuschild** [comment]
Fixed by #1829 and #1833
