### ISSUE TITLE
Handle expanded brew metadata storage (tags, thumbnails, etc)

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1838]
Storing metadata for brews works just fine if we are strictly using MongoDB.

We start running into issues with alternative storage sources however (e.g. Google Drive) because each system has varying limitations on the types and quantity of metadata that can be stored for a given document. Google Drive, for instance, allows 100 custom properties per file, but [only 30 can come from a single app](https://developers.google.com/drive/api/v3/properties), *and* they are each limited to 124 bytes, including the property name. This means longer properties such as thumbnail image links, long strings of tags, etc. simply can't be stored on Google Drive using the native properties. We will likely run into similar issues if we ever support GitHub, etc. as further storage options. See https://github.com/naturalcrit/homebrewery/pull/1777#issuecomment-960377433

We have two possible solutions as I see it:

1) We've had success with for storing the "style" tab for each brew, by simply embedding additional properties directly into the text of the file in some sort of header structure. I.e., the entire brew contents and metadata will be concatenated into one large string. This does mean that those particular properties will not be "indexable" or "searchable" directly from the database, but if users are hosting files in Google Drive we can't search all of Google Drive by property either. What does this mean for future "sharing" capabilities? Do we ever want to be able to hop onto Homebrewery and search for other published brews by tag? If so, we probably need to be satisfied that Google Brews will never be searchable in this way and users will be forced to transfer brews to our HB database storage if they want to have their brews publicly searchable.

2) We create brew "stubs" in the HB database alongside our other brews (suggested by @ericscheid at some point). Google Brew contents are saved to Google exactly as always, but we also store a "stub" in our MongoDB database that contains only a link to the Google Drive file, plus that extended metadata. This means it *will* be possible to make "published" Google Drive documents publicly searchable via our database. This also means sharding the storage of each Google document into multiple locations and neither one has the complete document information. A user who downloads their brew from Google will not find any of the related metadata attached. Maybe this is fine. We also run the risk of orphaned "stubs" if the Google Drive file is deleted by the user via the Google Drive interface, since Hombrewery wouldn't be notified of the deletion to update the stub appropriately.

One solution is more "unified" (make everything self-contained within the document itself), one is more functional (documents should just be the brew contents themselves, any other metadata is bonus that the HB tracks).

There are several issues that can't really be solved until we implement a solution here, but we need to carefully choose how we do this. Once we implement a storage strategy it becomes very hard to undo it later without losing data.

**Comment by jeddai** [comment]
We could take a JWT-styled approach to this and create an HB "file type". The file type would just be a single string, where it's `metadata`.`style`.`content` where the three segments are the full content of each segment base64 encoded. Not sure how big brews could get with that method though. This is a particularly easy solution because JS has the native `btoa` and `atob` functions to handle base64 encoding/decoding respectively.

**Comment by calculuschild** [comment]
I don't think we need to go as far as base64 encoding things (it also bloats the filesize considerably), but yes that is essentially solution 1) above.

I'm picturing this format which just builds on what we already do with the Style tab and uses pretty commonly-accepted syntax:

    ```metadata
    tags: monsters, dragons, 5e
    thumbnail: thumbnail.thumbnail.com/thumbnail.tmbnl
    theme: Legacy PHB 5e
    renderer: Legacy
    ```
    
    ```css
    .page .myCustomClass {
      color : blue; // This is in the "Style tab"
    }
    ```
    
    # My fancy Homebrew
    This is now the actual Markdown contents

**Comment by jeddai** [comment]
I might suggest a combination of 1+2 -- the file format with all of the data is stored in Google Drive, but a copy of it is stored in the Homebrewery database with an optional string MongoDB value that links out to the Google Drive copy. 

* When you load the document that was synced, if the file doesn't exist in Google Drive then it could warn the user and disable the Google Drive sync until the user sets it back up. 
* When deleting brews users would have to delete them in both places, but that would allow users to effectively "back up" their brews in Google Drive instead of move them there from the HB database.
* In the case of any discrepancies between the two (for users that might want to manually update their GDrive copies), whichever was updated most recently could be used, or we could choose pain and write something that handles merge conflicts :sob:

**Comment by ericscheid** [comment]
Store all the useful metadata in mongo (so searches and popular and other fun can be done on the hb website), and then also store the meta data in the document contents with the code-block method like we do with css. Maybe store some metadata in whatever metadata 3rd party systems support (although we have hit limits with that already, and different systems would likely have different limitations, and all kinda moot since we'd be putting all the metadata into the document-content stream anyway).

This also goes for the textfile downloads. If all I have is the textfile download, I should be able to manually re-build the brew from scratch (including tags, systems, description, etc). Similarly with the google doc file.

**Comment by jeddai** [comment]
I do want to express my concern over not storing the entire document in HB -- what happens if a user has their Google Drive document set to not be viewed by others? If it's marked as Published in the HB database and users found it, I'm pretty sure they would only have access to the stubbed information and not what is stored in GDrive.

**Comment by calculuschild** [comment]
We elected to not store the full brew text on HB for a few reasons:

1) Storage costs. The primary driver for adding Google Drive as a storage option was to keep storage costs down so we can keep this as a free service. Before we implemented Google Drive, our database size was increasing at an unsustainable rate. This is really the main reason and probably isn't going to change.

2) It simplifies conflicts. Some users edit their brews via Google Docs directly when on mobile/etc. so the two would not necessarily be in sync which could lead to more confusion for users. We could probably figure something out, but it's an added layer of complexity.

3) Data isolation. Some of the earlier requests for Google Drive or Github storage were because users didn't want to have to rely on the HB to hold their files. Whether that be concerns about the HB shutting down some day, worries about security, or just wanting "control", it seemed pretty clear that users wanted to be able to create documents that weren't at risk of someone else losing or deleting them by mistake. Keeping them completely separate from the HB database fit that desire.

With "stubs", all we do is when somebody marks a brew as "published" (ready to be publicly searchable), we make a database entry with the minimum metadata so it can be searched. The users still maintain control of their brew contents separate from HB, and it should only take minimal database space.

> what happens if a user has their Google Drive document set to not be viewed by others?

Any Google Drive document that is created via the Homebrewery is already initialized to be publicly accessible, otherwise the HB can't access it. As long as we have the file ID, which we can store in a "stub", the full brew contents will always be accessible unless the user deletes it or manually goes in and changes the accessibility from the GDrive interface, which in turn would block it from being opened from within HB anyway. If a stub is found to not connect to anything when we try to open it, we just show a message "looks like the owner has deleted this brew" and delete the stub.

I hope that makes sense.

**Comment by ericscheid** [comment]
IIRC, the google drive feature grew out of three main concerns:

1. some place "elsewhere" for people to store their brews, as guard against catastrophic failure on HB
2. leveraging the versioning that is built into google drive
3. imminent exhaustion of mongoDB storage quota as brews accumulated

Storing a copy of the entire brew also in MongoDB goes against point 3. Shunting many brews into google drive has helped with 3, as did compressing brew.text in mongoDB. But we probably don't want to go backwards now.

----

As to visibility ...

This is an unpublished brew of mine that is stored on gdrive:  
https://homebrewery.naturalcrit.com/share/1bbfxuSzWnfHq4uts_angYJZaxVPiNUo4UGpTUQSP66Vl

This is a published brew of mine that is stored on gdrive:  
https://homebrewery.naturalcrit.com/share/1D1mMuczJRqT10JNoWu0yZW447gC2xeIM3Md0yFJL-bKv

And this is my userpage:
https://homebrewery.naturalcrit.com/user/erics

Three things should be noted

1. you should be able to view both brews via their `/share` links — the 'published' vs 'not published' status means nothing right now (it will mean "make existence of brew visible on HB home page, search, etc)
2. you should be able to view both brews, even though they are in fact stored on google drive
3. the "dice mechanics" brew, although "published" does _not_ appear on my user page as a published brew .. because it is on gdrive, hb doesn't know about it

It is point 3 that would also be addressed by storing a stub in mongoDB, before we even get to the stage of making published brews visible via search etc.

**Comment by ericscheid** [comment]
Additional point regarding stubs .. assuming stubs are implemented as simply hollowing out the existing mongo record and flipping a flag in that record (vs deleting the original mongo record and creating a fully new stub record) .. the original `/edit` and `/share` links can be preserved via any roundtrip "move to gdrive" → "move to homebrewery".

Currently, roundtripping a gdrive move (aka "oops, no, didn't mean to do that just now") would destroy the original brew edit and share links. This has the unfortunate side effect of invalidating any links/URLs an author might have saved or shared to others (or published on their blog, etc).

**Comment by calculuschild** [comment]
Stubs are now fully implemented!
