### ISSUE TITLE
Document Social Embedding

### ISSUE THREAD

**Issue by jeddai** [naturalcrit/homebrewery#2012]
When document share urls are linked from various social platforms, an embed should be able to be obtained from the Homebrewery site. Embeds are typically handled by document head attributes, primarily opengraph values.

My proposal includes a few things:
- Fix https://github.com/stolksdorf/vitreum/blob/master/headtags.js
    - if you have multiple Meta objects it will duplicate them, which will break the embedding
- A default Homebrewery embed for the main page, v3 preview, and migrate pages
- Dynamic Homebrewery embeds for document share pages
- imageUrl document attribute that will display as the image for embeds

Example:
![image](https://user-images.githubusercontent.com/4909307/152890882-5c4933a0-4008-41e4-baf4-c1c26ac5c3a1.png)

**Comment by G-Ambatte** [comment]
Check #1777 - that PR added a bunch of OpenGraph meta tags in the header, but the change was reverted almost immediately due to an issue with how the thumbnail URL was being stored (see https://github.com/naturalcrit/homebrewery/pull/1777#issuecomment-960421531). This should be resolvable now that metadata is codefenced inside the brew text during storage; the original PR may be fine once any conflicts are resolved.

**Comment by jeddai** [comment]
Oh cool!

**Comment by G-Ambatte** [comment]
The original issue that PR #1777 was attempting to resolve was #820, for further reading.

**Comment by calculuschild** [comment]
If this is solved by #1777 then I say just revive that PR and go for it.
