### ISSUE TITLE
Inserting snippets unfolds code

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#2135]
Pretty much what the title says, I found that inserting any kind of snippet(images, spells, tables...) from the snippet menus unfolds all the code, which is quite annoying, and I don't think it was intended.

Happens in both unsaved and saved brews in both V3 and Legacy mode.

**Comment by ericscheid** [comment]
The various insert-snippet code could be updated to scan and note which pages are folded before doing the inserting, and then after inserting go back and selectively re-fold.

If I'm reading right from https://codemirror.net/addon/fold/foldcode.js we would use the `  CodeMirror.defineExtension("isFolded"...` function and then `CodeMirror.commands.fold`.

**Comment by Gazook89** [comment]
Is it worth the effort to save **fold states** to the brew so that they persist when a brew is closed and re-opened?  

If so, what about other the states of other "marks"?   Currently we don't have any other marks that change state, so it doesn't really matter, yet.

The link above doesn't work, but this is the rough sketch so far:

```js
const marks = this.refs.codeEditor.codeMirror.getAllMarks().filter((mark)=>{ return mark.__isFold; });

		const folds = marks.forEach((mark)=>{
			console.log(mark.find());
		});
```

I have this in the `handleInject` method of `editor.jsx`, and it's returning an array of editor positions that correspond to the folds before the brew text is split into lines.  I suppose that I can't just use that same array to re-fold the same lines, since any snippet injection is going to change line counts....it will need to know the line number of the injection and how many lines the snippet is.  (Right?)

references:
- https://discuss.codemirror.net/t/get-all-folded-sections-start-end-line-numbers/2864
- https://discuss.codemirror.net/t/cm6-fold-api-any-way-to-get-the-current-folded-regions/3152
- https://github.com/codemirror/codemirror5/blob/master/addon/fold/foldcode.js

**Comment by Gazook89** [comment]
It might be possible to do `getAllMarks()` before injection, get a unique `id` from each mark, and then find all of those unique `id` and fold them after the injection....to avoid doing math.   However, I'm not sure the `id` property i'm looking at stays the same--- and wife says it's bed time.  tomorrow...
