### ISSUE TITLE
add markdown superscript/subscript?

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2171]
https://www.reddit.com/r/homebrewery/comments/ujuvov/superscript_and_subscript/

Superscript can be done via html tags `<sup>...</sup>` and `<sub>...</sub>` but it would be nicer to have markdown style syntax.

Superscript and subscript are not currently supported in the markdown library we use. We could add it as custom syntax.

Reddit does it, like this:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2605467/167633802-8c964425-cdf6-4f69-ae6c-36d86582990d.png">

The optional wrapping in (parens) is useful for superscripts with word breaks, but also for ending a superscript without a word break (e.g. `e^(iπ)+1 = 0` for <kbd>e<sup>iπ</sup>+1 = 0</kbd>, or `0.5 × E = mc^(2)÷2` for <kbd>0.5 × E = mc<sup>2</sup>÷2</kbd>).

Some other markdown flavors do it slightly differently (i.e. wrapping the superscript in carets, like this: `E=MC^2^`.
https://www.markdownguide.org/extended-syntax/

Subscript could be indicated via tildes `~` perhaps, like `H~(2)SO~4` for Sulphuric Acid H<sub>2</sub>SO<sub>4</sub>.

**Comment by calculuschild** [comment]
Tilde `~` is already used for ~strikethrough~ text.

**Comment by Gazook89** [comment]
I know that I have used and recommended to others to use the strikethrough syntax for quick & easy custom inline styling.   Set `strikethrough` in the css to whatever styling you want, and then use `~~my fancy text~~` in your brew to more concisely do what `<span class='my-fancy-style`>my fancy text</span>` would normally do.  This works precisely because strikethrough isn't typically used for anything else.

Now with v3, it's almost as simple to do `{{my-fancy-style my fancy text}}` or `{{mfs my fancy text}}`.  

Maybe subscripts can be a combination like `text^.(my subscript)` or `^_`.    Or simply just create baked in classes `sup` and `sub` so that doing `{{sup my text}}` creates superscript and similar for subscript.  It's not *new syntax* but just a convenience class.

---

A little off topic here, but maybe in the far future it's possible for users to create a list of their own 'syntax' that overrides the built in syntax.  In the user profile or a single brews metadata, they could add to a list something like:

```
++{text}++ = "custom-span"
```
And then in their brew any `++here is my text++` would be rendered as `<span class='custom-span'>here is my text</span>`

I imagine this would be a nightmare for many reasons, but just spitballing.

**Comment by dbolack-ab** [comment]
Based on the merge, okay to close?

**Comment by 5e-Cleric** [comment]
> Based on the merge, okay to close?

yup
