### ISSUE TITLE
Admin page no longer lists brews due to commented search API function

### ISSUE THREAD

**Issue by SnappyTom** [naturalcrit/homebrewery#250]
Hi Scott,

The admin page is no longer listing brews. I can see it's because the /api/search function is commented out (homebrew.api.js). I find the admin page immensely useful, so I'd love it if the it still worked going forward!

Cheers,
Snappy

**Comment by stolksdorf** [comment]
Good point. I'll try and fix this with the next set of updates.

**Comment by SnappyTom** [comment]
Not sure if you're done with it, but I'd like to comment on the new admin page with a single search box. The old admin page which listed all brews was awesome. I even added a 'title' column to make it easy to identify the brews (the IDs aren't friendly).

Looks like the new admin page only offers a single-result search based on ID. I don't know about others but I feel searching by ID is a really difficult - how can I remember a random ID, and why limit the results to 1?

Listing the brews I think was really good - would you consider reverting to it? Adding a title column would be perfect I think. I think the current search is a step backward.

Thanks Scott!

**Comment by stolksdorf** [comment]
The way I was implementing the brew listing before was very flawed and actually was use-able in Production due to the sheer number of brews. I needed to build an API that supported search and pagination, one thing lead to another and I'm currently in a nearly complete re-write of the whole project. 

Much of the project's internals haven't gotten much love since v1 and were still very much coded like a weekend hobby project, which made building new features very tedious.

For the v2.7 release I patched up the admin page so I can at least use it for support until I'm done with the improvements in v3, which will have full search and paginated listing.

FunFact: The brew lookup tool is really helpful for support because many people mis-copy their edit/share id and leave off the last few characters, so this tool let's me find those. I can also find the edit from the share id and vice versa.

**Comment by SnappyTom** [comment]
Thanks for the explanation Scott - looking forward to v3 :)

**Comment by 5e-Cleric** [comment]
6 year old issue, i've never opened the admin page personally, but wasn't this fixed back then?

**Comment by SnappyTom** [comment]
I can't run v3 locally due to database version issues, so I'm not sure if it was fixed in v3, but judging by Scott's comment, he did not have a use for the functionality I was asking for, so I doubt it. You can close this issue if you like.
