### ISSUE TITLE
save error after adding thumbnail logo to settings

### ISSUE THREAD

**Issue by DMHWolf** [naturalcrit/homebrewery#2500]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75356:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75665:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/0GWx4yK7VoJY"
}
```
```


### Your description of what happened:

tried to save after adding my png logo thumbnail (hosted on google cloud) and it failed.

**Comment by calculuschild** [comment]
How long was your image url?

**Comment by Gazook89** [comment]
Maybe easier question is, what was the image URL?

**Comment by DMHWolf** [comment]
thanks... it was https://storage.googleapis.com/www.bchowl.com/resources/images/bchowllogo.png

It worked when I logged out and back in again

**Comment by Gazook89** [comment]
77 characters.

I couldn't replicate the issue in a new brew.  I wonder if it was just coincidental that it happened when updating the thumbnail URL, and it was just a 'regular' server burp?  Someone else should see if they can replicate, otherwise maybe just close this issue since it seems resolved but revisit if we get another encounter.  Up to @calculuschild
