### ISSUE TITLE
[LOCAL Only] Change Google Drive folder name

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2555]
### Your idea:

As local installs can use the same Google account is the live website, this will result in two Homebrewery folders in Google Drive, with no easy way to differentiate the two. Adding the ability to modify the folder name, ideally through a `config/local.conf` or similar file, will make it much easier for those of us running Google-linked local installs to locate our files.

**Comment by calculuschild** [comment]
Oh really? My local install uses the same folder.

**Comment by calculuschild** [comment]
If you have different google credentials that might be it, because when your local homebrewery searches for an existing folder it can't find it anymore and so makes a new one.

Regardless, you can just manually go in and rename the folder in your drive. I don't think we need a whole separate config here to do something you can easily do just through Google.

**Comment by calculuschild** [comment]
Closing this. Easily solved by just going into Google Drive and renaming your folder.
