### ISSUE TITLE
Homebrew isn't saving

### ISSUE THREAD

**Issue by Bramble892** [naturalcrit/homebrewery#2590]
### Error Code

```shell
Error: Internal Server Error


require<.superagent</Request/<@https://homebrewery.naturalcrit.com/homebrew/bundle.js:76355:19
require<[9]</Emitter.prototype.emit@https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20
require<.superagent</Request.prototype._end/xhr.onreadystatechange@https://homebrewery.naturalcrit.com/homebrew/bundle.js:76664:10

{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/GNNdAK9ekiCI"
}
```
```


### Your description of what happened:

Homebrew isn't saving.

**Comment by calculuschild** [comment]
I'm assuming this is fixed by now, but the error was you had an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)


That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.

**Comment by Bramble892** [comment]
Thank you for your help
