### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2729]
### Your idea:

The FAQ page has the following question and answer:

![image](https://user-images.githubusercontent.com/19826659/224630336-01c341da-cf68-439e-8f6e-c9c21bd549e8.png)

> Q. How do I log out?
> A. Go to https://homebrewery.naturalcrit.com/login, and hit the “logout“ link.

While this technically correct, since this was written, we have added the LOGOUT button to the Account menu, and the FAQ should be updated to reflect the current reality.

![image](https://user-images.githubusercontent.com/19826659/224630597-d077b633-6a29-4802-be5c-8f72f17b7094.png)

**Comment by Gazook89** [comment]
Question is, is this even a "frequently asked question" at this point?  Now that we have a much more intuitive process for logging out, I think we can just remove this question.

**Comment by 5e-Cleric** [comment]
Perhaps this issue should stay as a permanent one, i believe the FAQ should be updated every time big changes come, like this question:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/91662974/230224472-8bd918fe-ea5b-456e-85b6-90b76df451b2.png">

Which is in process of being unnecessary.

Other possible changes i would see are:

- Adding a little list of "brew not found", "server busy" and some other server errors, and possible explanations.
- The question about the editor occupying the entire window, didn't that get fixed?
- Maybe add a list of useful documents, like the v3 reference doc? maybe apart from the FAQ
- Add a password lost what to do, in order to explain why there is no password recovery, and the mod mail to ask for help?

**Comment by 5e-Cleric** [comment]
Progress in this issue will be kept track in #2816, closing issue.

**Comment by calculuschild** [comment]
Reopening so we have a space to hold discussion specific to this issue until it is resolved.

**Comment by 5e-Cleric** [comment]
Another FAQ:

### Can i sell content created with this tool?

> We reccomend you seek some form of legal counsel to answer this question, that said, we can give you some guidelines:
> 
> If your document resembles the style of any book published by a company(such as Wizards Of The Coast) check their Fan Content, Ownership, or Licensing policies, or any simmilar policy the company might have regarding copyright  and licensing, there you should find information on wether you can sell such content and under what conditions.
> 
> In the specific case of Dungeons and Dragons, we link here their [Fan Content Policy](https://company.wizards.com/en/legal/fancontentpolicy) and [Dm's Guild Help page](https://help.dmsguild.com/hc/en-us) which should provide enough information to come to some understanding about the matter.
> 
> If you don't follow the appropiate regulations, legal action from the owner of the original system could be a risk for you.
> 
> Please don’t pull us into any legal battles! This is a free tool and you are responsible of anything you do with it, or any document made with it.


What do you think of this draft?

**Comment by ericscheid** [comment]
The answer should, foremost, be addressing whether naturalcit.com or The Homebrewery is claiming any rights or restrictions to content published via The Homebrewery. Which we don't.

Only then should the answer go on to advise that THB doesn't speak for other copyright holders and provide guidance there.
