### ISSUE TITLE
Full-page Table-of-Contents

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#304]
So, after taking a look at [the request for dot leaders](https://github.com/stolksdorf/homebrewery/issues/301) in the table of contents, I found a solution that seemed to work. Now, I've extended the toc class to work with the PHB full-page table of contents if you would like to add as a snippet (or not). In this case it would probably make sense to create a separate toc class as the one I use has to override a few things to make it work. Hope this is helpful in some way.

**Share Link** : http://homebrewery.naturalcrit.com/share/Sy-z2DBve

![image](https://cloud.githubusercontent.com/assets/5878534/22340473/946a209a-e3bb-11e6-8421-b0091d03abb6.png)

**Comment by stolksdorf** [comment]
The original TOC was just hacked together one morning. In v3 there will be a nice TOC class with generator. Thanks for the code, I'll use it as a base

**Comment by DoctorDan1986** [comment]
Here's a thought - why not add a function to tie pages together with a page number so that whatever page they are linked to will auto-update the page number in the TOC...or wherever page numbers are referenced?

I'm working on some pretty big brews at the moment, and sometimes due to formatting or inspiration, page numbers change for references...which means that I have to go through the entire brew hunting page numbers to change them.

**Comment by stolksdorf** [comment]
@DoctorDan1986 you can already do this. You can wrap whatever title or block of code you want in a div with an id, and use that for the link instead of the page number.

**Comment by DoctorDan1986** [comment]
Is there a page with all the available commands for the brewery somewhere?

**Comment by stolksdorf** [comment]
The snippets are there to show some things you can do, mostly things specific to Homebrewery. Other than that, there really isn't commands, this is just HTML.

**Comment by DoctorDan1986** [comment]
You've mistaken my meaning a bit.  Okay, so I can wrap headings with a div id, and I can jump to that, which is super helpful for a web-only book, but what I really want is a dynamically updating TOC page number - so that if I, for example, have an enemy bestiary start on page 100, but add a new section between the TOC and page 100 that adds two new pages in the middle of the book, the page number as shown on the TOC for the bestiary will dynamically update to reflect the two new pages so I don't have to go through and manually alter each individual page number.

**Comment by stolksdorf** [comment]
I understand what you mean, but I will not build it. Automatically modifying user's content is an easy way to introduce unexpected behaviours that frustrate users. 

The two ways I see the TOC being used is A) You use the sippet, which autogenerates it, if you make changes, remove the TOC and use the snippet again. B) You want fine-grain control over what is in the TOC and how it looks, then you will have to manually update it when you make changes.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
