### ISSUE TITLE
Fix text editor styling

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3322]
<img width="937" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/a00cff2b-f1c2-4283-a78d-2b9aed3206a1">

**Comment by 5e-Cleric** [comment]
@dbolack-ab Could you add a fix for the non-code block highlight as well?

**Comment by 5e-Cleric** [comment]
The comment highlight is not fixed yet, i believe

**Comment by calculuschild** [comment]
By "comment" do you mean "code"?

The `code` syntax highlighting is built into Codemirror, so might need to report that one to Codemirror rather than fix it here.

However, it's the same behavior for italics, bold, etc.:

![image](https://github.com/naturalcrit/homebrewery/assets/5878534/60b0d6aa-664a-44e3-b98a-6ae7e4813810)

**Comment by 5e-Cleric** [comment]
If it's a codemirror bug, i think we might want to keep this open, as we do with chrome bugs

**Comment by calculuschild** [comment]
For the Chrome issues, the main reason I have that open is because it shows we are aware of the issues, and are still waiting for them to be resolved, so we don't get as many duplicate reports. Though we could probably reduce it down the one "master" issue that points to all the Chrome issues and close the rest.

I know some projects just have a tag "external project" or similar to mark issues like this and just... Leave them open forever.

**Comment by Gazook89** [comment]
Also, I'm not sure this is 'broken'.  It is just highlighting in the editor before the syntax is 'closed'.  Which is probably a good thing-- it signals to users that you have started a syntax type.   If you didn't intend to start a new syntax/tag, you would escape it:   `Here is my \*non-italic text`.  

Because of this, i doubt CM would make changes.  Plus, this would change the behavior in a *lot* of editors besides HB.
