### ISSUE TITLE
Download as .txt from EditPage

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3335]
Right now, users without an account can't use the download as txt, ironically, users without an account are the ones who could benefit most from this feature, particularly if #3289 goes through.

we shall change the navigation get pdf  component to a dropdown, with the current getpdf element and a get txt one using the same function we already use in userpage.

**Comment by calculuschild** [comment]
> Right now, users without an account can't use the download as txt

This is not true. All users can download as txt, whether logged in or not.

**Comment by ericscheid** [comment]
If the brew is saved then the `Download` option is available by first clicking the `Share → View` nav menu item, and then the `Source → Download` option. It's not obvious, but it is possible.

What is not available is the `Download Brew` button on a brewItem card on a `/users/` page, as the brew has not been associated with a user as yet.

Similarly, there is no option to download if the brew has not yet been saved at all. Which is not unreasonable.

On the `/new` page, the `Get PDF` nav item can't also support a `Download Text` option because it's a http request to the server for `/download/:id` (and the brew only exists in localStorage, not a `/edit/:id`). Not unless we engineer an entirely client-side download text option (not difficult, but is forking functionality and so is architecturally unsound).

**Comment by 5e-Cleric** [comment]
Right, checked the edit page, but i guess they can access the share page, nvm then

**Comment by calculuschild** [comment]
That said, I don't think it would be unreasonable to make the download link visible on the edit page. It is not super obvious that it is hidden away on the share page. I'm not sure how we would best fit everything, but if there is some reorganization of the nav bar that makes sense I'm ok with that.
