### ISSUE TITLE
Multi-page variable use doesn't work when parsed to PDF

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3435]
Here i describe two variable bugs reported by @TheDungeonMathster in the Discord Of Many Things:

## 2. Multi-page variable use doesn't work when parsed to PDF
This code works fine in the brew but fails in the PDF render
```
[foo]:bar

$[foo]

\page

$[foo]
```

**Comment by G-Ambatte** [comment]
On 2... dammit. I just looked at PrintPage and realized that it effectively uses a copy/paste of the BrewRenderer code, so all of the changes and updates that were made to make variables work across pages just did not get applied to the Print output.
I suspect the best way to fix it will be to extract those functions from the BrewRenderer to a separate component that can then also be accessed from PrintPage, so that the functions only exist in one place and any future changes effect both renders.

**Comment by ericscheid** [comment]
This issue needs to be split into two unrelated issues, because the first thing has nothing to do with variables.

<img width="1493" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/2605467/365ebce3-833e-4d8d-9a09-d9c55d09471e">

**Comment by 5e-Cleric** [comment]
Print page does not exist anymore, so... issue fixed!
