### ISSUE TITLE
Links in ToC broken with 3.13.0 release

### ISSUE THREAD

**Issue by ewirtz65** [naturalcrit/homebrewery#3547]
## Links in ToC broken with 3.13.0 release

**Share Link** : https://homebrewery.naturalcrit.com/share/fFPgV7Rj1YC2

 Clicking a link in the generated ToC opens a new tab instead of jumping to the location.

Worked an hour or so ago, before the new client was pushed out.

Chrome is up to date
Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by G-Ambatte** [comment]
I believe that this is related to the addition of DOMPurify - see https://github.com/cure53/DOMPurify/issues/317

**Comment by 5e-Cleric** [comment]
Huh, thought i had filed an issue on this. Wanted it fixed before release, but we got a comunication problem.

**Comment by dbolack-ab** [comment]
Please confirm fix. Thank you.

**Comment by G-Ambatte** [comment]
I believe that this issue was due to the overly restrictive DOMPurify stripping attributes from the ToC link elements, and the issue is no longer present. PR #3548 achieves the same purpose as the original intention of the DOMPurify PR, but without being nearly as restrictive - testing has not shown any of these issues returning.

**Comment by dbolack-ab** [comment]
I'm going to leave this open until #3548 is applied or closed.
