### ISSUE TITLE
Table of contents UPPERCASE titles un-uppercaseable!

### ISSUE THREAD

**Issue by misthero** [naturalcrit/homebrewery#3572]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

When generating the table of contents (Text editor -> Table of contents (beta) ->  Table of contents (beta)) 
H3 titles are "uppercased", while before they where respecting the formatting of the actual title in the editor and it's capitalization.

Maybe this is something that have to do with making things 5e like, but I selected Pathfinder in the brew information, I'm using custom CSS to make things similar to pf2e but in this case is not a css issue, the renderer automatically uppercase the h3 in my brew.

TOC BEFORE:
![image](https://github.com/user-attachments/assets/7604d3fd-e75e-453a-8a32-130c742d81c1)

TOC AFTER:
![image](https://github.com/user-attachments/assets/24cdb65e-6498-4958-bd08-78c7cfbc3cf2)

text is UPPERCASE in html, not via css, cannot easily override...
![image](https://github.com/user-attachments/assets/8dae349f-5e38-4c84-b15e-59f55a78256e)

**Comment by 5e-Cleric** [comment]
That is due to your own CSS, not us, there is no official pathfinder theme, so it may come from the copied theme, find the rule that will target that and remove it, you may go into your style tab and search for `text-transform`. If you don't find anything, please share your brew so we can take a look.

**Comment by misthero** [comment]
> That is due to your own CSS, not us, there is no official pathfinder theme, so it may come from the copied theme, find the rule that will target that and remove it, you may go into your style tab and search for `text-transform`. If you don't find anything, please share your brew so we can take a look.

sorry to insist, but there is no text-transform css rule affecting that element in the TOC or any container elements, I sent a screenshot showing you the html, that is not affected by the css. The html in the ispector shows how the text is in the html, but is not entered uppercase

![immagine](https://github.com/user-attachments/assets/542b1252-dfb2-4e0a-b2c1-806fdad33b84)
here you can see the text in the editor, the text in the toc, the text in the html corresponding to the select element. There is also the style filtered with the keyword "text" to prove that there is no rule for that element and upper elements saying it should be uppercase.

BUT the h3 is uppercase in the renderer in the correspoding page 

![immagine](https://github.com/user-attachments/assets/a3383589-a3b8-494d-a614-7047453056f7)
as you can see the html is correct here (not uppercase) and the css is making it uppercase

so, what I think, but I can be wrong, I fear is that the TOC is generating from the uppercased "output" and not from the source html or the source editor.

**Comment by 5e-Cleric** [comment]
Per my last message:
> If you don't find anything, please share your brew so we can take a look.

**Comment by G-Ambatte** [comment]
As I understand it, the crux of the issue is that if a user has a style that changes a header to uppercase, then when the ToC is generated, the ToC entry is also in uppercase.

Digging through the code, it appears that [this line](https://github.com/naturalcrit/homebrewery/blob/4fe38e3929256ee1bf1cacd4d9264226d8f44d9a/themes/V3/5ePHB/snippets/tableOfContents.gen.js#L38) is the heart of the issue - when the BrewRenderer iFrame is being parsed for headers, the `innerText` property is passed as the ToC entry content - however this includes any `text-transform` applied through styling.
A potential alternative might be to use `innerHTML` instead, although this approach will have issues if the entry contains inline styling.

![image](https://github.com/user-attachments/assets/c104032d-db19-453d-b886-741265a71d6c)

![image](https://github.com/user-attachments/assets/5e3b1f2c-ced9-43e2-9cf4-9f21997e5c2d)

**Comment by misthero** [comment]
I can confirm my theory, if I enter in the style editor:

```
.pages .page h3 {
   text-transform:lowercase;
}
```

the toc will take it even if there is no h3 

this is the brew

https://homebrewery.naturalcrit.com/share/OPBqOHMt7sKn

**Comment by misthero** [comment]
> As I understand it, the crux of the issue is that if a user has a style that changes a header to uppercase, then when the ToC is generated, the ToC entry is also in uppercase.
> 
> Digging through the code, it appears that [this line](https://github.com/naturalcrit/homebrewery/blob/4fe38e3929256ee1bf1cacd4d9264226d8f44d9a/themes/V3/5ePHB/snippets/tableOfContents.gen.js#L38) is the heart of the issue - when the BrewRenderer iFrame is being parsed for headers, the `innerText` property is passed as the ToC entry content - however this includes any `text-transform` applied through styling. A potential alternative might be to use `innerHTML` instead, although this approach will have issues if the entry contains inline styling.
> 
could an alternative be using `textContent` instead of innerText or innerHTML?

**Comment by calculuschild** [comment]
`textContent` might do the trick.

I didn't know `innerText` retained changes due to CSS formatting but it looks like it does.

**Comment by G-Ambatte** [comment]
Looks promising: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext

It should be relatively simple to throw together an experimental branch for testing - I'm at work at the moment, so if no one else does it in the next six to eight hours, I'll see what a `textContent` ToC generator variant looks like.

**Comment by G-Ambatte** [comment]
Initial experimentation looks like `textContent` should work.

![image](https://github.com/user-attachments/assets/33302888-8346-449e-af33-441a70b68172)

**Comment by G-Ambatte** [comment]
Managed to snatch a few minutes during a late lunch break to throw together a quick PR. Initial testing looks like it solves the issue without introducing new ones!
