### ISSUE TITLE
Discrepancy with link building in userpage

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3593]
In the userPage, or brew page, the link for a brew, both edit and share is the edit or share id of said brew.

However, in the recent brews nav dropdown, the link corresponds to the user google Id + edit or share Id.

This discrepancy should be fixed either way.

preferably without displaying the google Id.

Relevant files are brewItem.jsx and recentItem.jsx

**Comment by calculuschild** [comment]
There is an edge case if it is an old Google Brew before we introduced Stubs. Those should be gradually disappearing because we add a stub entry in Mongo when they are edited (maybe also when viewed? Can't remember now).

But I believe there are still some out there. Google brews that don't have any record in our database yet. Those links still require the Google ID.

**Comment by 5e-Cleric** [comment]
> There is an edge case if it is an old Google Brew before we introduced Stubs. Those should be gradually disappearing because we add a stub entry in Mongo when they are edited (maybe also when viewed? Can't remember now).
> 
> But I believe there are still some out there. Google brews that don't have any record in our database yet. Those links still require the Google ID.

I believe the thing here is that one of these does not check for stubs before making the link

**Comment by 5e-Cleric** [comment]
Fixed this in #3793
