### ISSUE TITLE
Emojis don't like to be hidden

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3604]
| Operating System | Browser | Renderer |
|:----------------:|:-------:|:--------:|
|      Windows     | Chrome  |    v3    |

### Description of the issue

Any page that uses the new emoji syntax will not stay folded when using the gutter arrows to fold. When using the Fold All editor tool or keyboard shortcut, the pages fold correctly, but unfolding any individual page will also unfold any page containing the new emoji syntax.

**Reproduction steps:**

1. Put the source code provided into a new brew
2. Use the Fold All function (`CMD/CTRL+[`) or click the Fold All toolbar icon.
3. Click the gutter arrow to unfold page 1.
**RESULT:** Page 1 AND Page 2 unfolds.
**EXPECTATION:** Only page 1 unfolds.

4. Repeat step 2.
5. Click the gutter arrow to unfold page 3.
**RESULT:** ONLY Page 2 unfolds.
**EXPECTATION:** Only page 3 unfolds.

### Code

```gfm
\page

:df_d2:

\page
```

**Comment by 5e-Cleric** [comment]
Right now there is a nifty error:

### Expected behavior of `foldAll`:

![image](https://github.com/user-attachments/assets/4ed05cab-b69f-4f1c-aad7-c8ca05e470bf)

### Actual behaviour:

![image](https://github.com/user-attachments/assets/70056b57-500f-4d55-8d2c-ba7b4a3da64d)


This issue is not caused by this PR, but what the hell?

The emoji stuff seems to be solved.
