### ISSUE TITLE
Markdown - adding classname to elements

### ISSUE THREAD

**Issue by vlos** [naturalcrit/homebrewery#403]
I recently started playing with some markdown converters (nodejs) as I'm working on a GMing tool. To clean up the css and such I wanted to add class styles to blockquotes, specifically so I can create GM Note boxes and Description boxes easily.

**Markdown Extra** allows you to add "Id's" to elements and PHP markdown allows you to add classes.  I grabbed the "Showdown.js" converter and with some simple reg-ex was able to add classnames to block quotes using the below syntax.

Just thought I would share as it may make it easier for your project to customize the markdown css as I know you are/were having problems with it.

I am looking to modify it a bit more to allow classes to be added to other elements as well.

### Additional Details
Classname Appended to the first line of the start of a blockquote,
<code><pre>\> some blockquote text {: classname}
</pre></code>
As you can see by the screenshot below I can easily nest the boxes and other elements.
![Example coding](http://miniworld.com/temp/markdownExample.png "Example coding")
</details>

**Comment by Gazook89** [comment]
I believe this is added to v3 with custom syntax.  Particularly PR #1476 and curly injection.

**Comment by ericscheid** [comment]
Curly-injection works to apply the `{curly-items}` into the preceding adjacent sibling element, not into the containing element.

Thus, an author could brew `Hello **world**{color:red}` and the `<strong/>` element gets injected.

That said, there is a suggested variation to `{curly-inject}` to target the containing element, specifically the `<div class="page">` element that is wrapped around each page of content. #1489. Using a leading `:` or other symbol could be used to say "target containing element instead of preceding element.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
