### ISSUE TITLE
Brew Render & Chrome Print Performance with High Page Count 

### ISSUE THREAD

**Issue by brianfeister** [naturalcrit/homebrewery#407]
Hey @stolksdorf, wanted to open this, not to create more headache for you but to hopefully understand where this project is headed and whether I want to contribute on a larger scale in order to help get this to where I want it to be (which I'm hoping is **also** where you want it to be! 😁)

I am (perhaps very foolishly) using this as I mentioned in #395 to generate very large files, two of them that are about 150 pages each. Right now, I think I'm far enough down the rabbit hole that I will finish with this tool even though I discovered late in the game that documents of this size cause Chrome's rendering to PDF to become unresponsive and nearly lock up completely. 

I was wondering if you could share your experience with this and let me know whether you think this is an "unsolvable" type of problem? In the Electron version of the app with a Desktop application shell, do you think there is a node module that can print to PDF via a Headless version of Chrome (probably creates a risk for rendering inconsistencies) that doesn't lock up the browser? Also, I guess the high page count creates a question for the over-arching architecture of the codebase and whether lazy-loading would be reasonable for handling page renders so that only the current page and then + / - 5 or 10 pages are actually rendered. 

It's not my intention to be a diva / time-consuming "customer", but I'd love for this to be a legitimate open-source publishing platform. I think the lazy / partial document rendering should probably be doable, but question of PDF output is a bit more of a concern / risk and I have my doubts about whether or not I should continue. 

For what it's worth, here are some features I've finished or am already working on in via my local hack-job that might interest you:

- [x] Working 300dpi CSS & HTML (involves usage of `zoom` and a LESS multiplication factor of `4.16666`, the multiplier from 72dpi screen resolution, to 300dpi print resolution (_also this has been verified by my printing vendor -- I was worried they would shoot down the resulting 300dpi PDF as "not fit for print_)
- [ ] "Page number offset" - brute-forced this in for now, allows a `?start_page=50` param to band-aid the high page count limitation and do auto page numbering with an offset (not possible via CSS `counter`s, wasted alot of time trying)
- [ ] Option to auto-handle page footer numbering rather than forcing the user to remember

**Comment by stolksdorf** [comment]
Thanks for the very in depth response.  I'll dive in a bit more later, but I thought I'd quickly share some insight, 

So Partial Page Rendering (PPR) has already been implemented. However it causes significant issues. Since style tags and various other HTML modifiers are stored on a page-by-page basis, disabling some pages can actually cause certain styles to stop working. The most frustrating side-effect is that it actually hides HTML bugs. Nearly every issue you see here saying "It was fine during edit, but when I go to print it breaks!" is because they had bad cascading HTML and the PPR stopped the cascade. 

(*Side Note:* The new rendering method in v3 makes PPR 100% viable and will be used by default)

I have never experienced the Print-to-PDF crashing before. it's definitely creeping into one of those "unsolvable" problems. So with v3 rendering, each page could be considered it's own stand-alone target for exporting, which makes threading it with an offline lib possible. However I have very little luck getting any lib export to PDF working as well as Chrome (hence why I gave up on it). The tricky part is usually external/custom fonts or images people try and use. 

A quick fix, and mostly just for your specific use case, is adding the ability to limit which pages get rendered on the `/print` page. It's pretty easy to add, but this will break if you use `<style>` tags outside the pages being rendered. 

It sounds like you are doing a one-off export, so you could also download the rendered HTML from the print page and use another site or a downloaded lib/tool to convert to PDF for you, although I highly doubt it will look the same as chrome. PDF rendering is more of an art than a science it seems.

And re:footers. Auto-incrementing footers have already been added. check out the [docs on css counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters) if you ant to fine-tune how they work. eg. `<style> #p15{ counter-reset : counter(phb-page-numbers); } </style>`

**Comment by brianfeister** [comment]
Ah, sorry I failed to explain that. The `.pageNumber.auto` doesn't work for my use case because I'm being forced to chunk a single document into many and there's no way to use a `data-attr` or similar to force an offset into the CSS `counter`. I just did it server + client side with a `?start_pg=50` offset.

**Comment by dbolack-ab** [comment]
Given the time that has passed since this was filed - is this still an issue?

**Comment by brianfeister** [comment]
Haven't looked at my project in years and don't have the source file any more. Looks like you're hoping v3 fixes but it's not going to be something I can test at this point. Apologies for that

**Comment by dbolack-ab** [comment]
Given the age of this issue and that I can repeatedly export 200+ page PDFs reliably, I am going to close this.
