### ISSUE TITLE
Bullet Points Either Don't Work Or Are Too Close to Text

### ISSUE THREAD

**Issue by vexir** [naturalcrit/homebrewery#526]
As subpoints for text that is wrapped with `> - **text**`, bullet points underneath that text don't work. If you double up on the bullets, they are too close to the text.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/B1W4EvcOp-

See the skills section. If you were to change one of the bulleted list items to a single bullet, for example:

`> - - Animal Handling +4` to `> - Animal Handling +4`

the bullet just disappears.

**Comment by vexir** [comment]
bump?

**Comment by ericscheid** [comment]
OK, this is caused by some squirrelly CSS code that wasn't expecting sub-list items in monster blocks.

Insert this code into your brew:

```
<style>

  .phb hr+blockquote ul {
    padding-left: 0;
  }
  
  .phb hr+ul>li {
    text-indent:0; 
  }

 .phb ul li li {
    margin-left: 0.5em; /* adjust for space before the sub-list bullet */
  }
</style>

```

----

BTW, the way you've marked up sub-lists isn't right. Markdown just wants the sub-items to be indented, you don't enter `- - Animal handling` ... this is important because it will affect what CSS works and doesn't work.

So, instead of this:

```
> - **Skills**
> -  - Animal Handling +4
> -  - Athletics +5
> -  - Survival +4
> -  - Persuasion +5
> -  - Deception +5
```

.. you code this:

```
> - **Skills**
>   - Animal Handling +4
>   - Athletics +5
>   - Survival +4
>   - Persuasion +5
>   - Deception +5

```

(The difference is that the former produces `<li><ul><li>list item +n</li></ul</li>` for every sub-list item, which will get confusing).

**Comment by ericscheid** [comment]
Closed, unusual CSS provided for unusual markup.
