### ISSUE TITLE
Request: change the order of a user's brews on title page?

### ISSUE THREAD

**Issue by Gadget2020** [naturalcrit/homebrewery#562]
Can the order be changed from alphabetical to...
- most recent
- oldest
- last edited
- number of views

It might be nice to also only be able to 'edit' un-published brews? Or only edit the metadata? Perhaps also change the trash icon to an un-publish one? (can only trash un-published works)
There is also the tic box for editions in the metadata: might be nice to show that on the title page too?

**Comment by ericscheid** [comment]
See #1459

**Comment by G-Ambatte** [comment]
>  Perhaps also change the trash icon to an un-publish one? (can only trash un-published works)

That is an interesting thought.

**Comment by Gazook89** [comment]
Didn't want to create a new issue for this but thought I could append it here:  currently the brew description returns as "undefined" on the user page and should be fixed to display nothing.  

But to recap this Issue and what has been done since:
- [x] The user page now has *Sort* functionality so that brews can be sorted in ascending or descending order by Title, Created Date, Updated Date, and Views. 
- [ ] change trash icon to multi-step functionality:  If published, trash can un-publishes...if un-published, trash can deletes brew.
- [ ] add systems/tags to brewItems on user page.

**Comment by Gazook89** [comment]
On brewitem.jsx line 110, I think this would fix brew item descriptions showing as 'undefined':
```
<p className='description'>{brew.description !== undefined ? brew.description : ''}</p>
```

**Comment by G-Ambatte** [comment]
It would probably be better to branch out the remaining problems into separate issues so they can be tracked and resolved independently of each other.
That said, the undefined description bug should be relatively simple to correct, although from memory I think `{brew.description || ''}` is both functionally equivalent and more elegant than `{brew.description !== undefined ? brew.description : ''}`.

I've been meaning to take a look at the Published Brew deletion issue. Again, I don't think it is necessarily complicated, but I could be wrong about that.

**Comment by calculuschild** [comment]
Just my two cents, I'm not a fan of fragmenting behavior where the same button gives two different behaviors, or "hiding" functionality behind another step.  I foresee users being confused "where is the delete button for my published brews?" Or conversely, "there is an unpublish button for my published brews, but not a publish button for my unpublished brews?"

**Comment by calculuschild** [comment]
Closing. The initial issue has been solved with brew sorting on the user page. I think hiding the trash button on published brews is going to cause more confusion than it solves.
