### ISSUE TITLE
Save to PDF Issue using Chrome - Columns shifting

### ISSUE THREAD

**Issue by feralfowl** [naturalcrit/homebrewery#566]
I just finished creating a class and am working on getting the PDF, but I've been struggling to get the formatting right. As soon as I get to the print screen, I follow all the directions on the homepage, but still end up with a couple paragraphs pushed to a 3rd column off the page.

**Share Link** :https://homebrewery.naturalcrit.com/share/H174jgGX-z

![homebrew class error](https://user-images.githubusercontent.com/34248383/33569213-8efd5126-d8ee-11e7-9af7-746917b52017.PNG)

</pre></code></details>

**Comment by ericscheid** [comment]
That last paragraph is longer than the space available at the bottom of column-2, so it auto-flows to column-3.

This can happen because different environments have slightly different font-metrics, and your paragraphs are right on the edge of spilling over. This sucks. Fonts suck.

You could try squeezing out some excess space above which is pushing down the available space, or try word smithing some of those bullet points so they take only one line instead of two (thus tweaking that one sentence ¶ back into column-1, freeing some space).

Also this might help..

```
.phb p:empty { display: none; } /* zap that blank space under the table */
.phb .classTable table { margin-bottom: 0; } /* zap more blank space off that table */
```

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @feralfowl
