### ISSUE TITLE
Text is overflowing off the page rather than continuing down the column.

### ISSUE THREAD

**Issue by AbelardtheBard** [naturalcrit/homebrewery#592]
http://homebrewery.naturalcrit.com/print/HyvGCJuQG?dialog=true

**Comment by wyvernsforhands** [comment]
I'm also having this problem! (My excuse for the stat block's content is that I'm running a game for bards.)
[https://homebrewery.naturalcrit.com/print/Hk7_WuPMBf?dialog=true](url)

**Comment by ericscheid** [comment]
Not seeing problem as described in post title.

Am seeing one page with too much content overflowing into column-3 .. so that should be fixed with a `\page` break.

I can imagine one edge-case that fits the description .. column-2 contains a huge paragraph (or multiple "paragraphs" joined together with `<br>` instead of blank lines) .. this would cause the too-large ¶ to bump to col-3, leaving the too-small space in col-2 blank.

Closing.
