### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by PSDNDFUN** [naturalcrit/homebrewery#724]
Hey I was wondering if you guys knew why the file size has been increasing lately when I turn my homebrew into a pdf.  Normally it was around 1 MB however in the past 2 months something happened where the file size is now around 50 MB.  Also I did use the work around for the tables that one nice guy on here mentioned and it worked.  I mention it because I don't know if that is the cause but I don't think so.  One of my homebrews doesn't use class tables and experienced a large increase in file size as well.

**Comment by Gazook89** [comment]
Going to close this old issue since there are more productive discussions [here](https://github.com/naturalcrit/homebrewery/issues/1087) and [here](https://github.com/naturalcrit/homebrewery/issues/1311).  I do believe some steps have been taken between 2018 and now to improve file sizes/load times.
