### ISSUE TITLE
Issue with adblock

### ISSUE THREAD

**Issue by perilomo** [naturalcrit/homebrewery#774]
## Problem with shared pages while adblock is on

So I've been working on a page at work for the entirety of the day and decided to finally preview it at home, however all I am met with is a blank white page with nothing to display.
I've started fiddling with my google chrome (As the share did work on Firefox, just the formatting was off) and fogired that by disabling AdBlock extension it suddenly works =/

I have found a similar issue:

Same as : Blocking Google Analytics breaks shared pages #88

However it was not reproducible and the issue was closed. I can consistently reproduce the issue on my home PC and I am not sure why that is (I suspect a filter?)

**Share Link** :

https://homebrewery.naturalcrit.com/share/ByrCxA2cX

**Comment by Gazook89** [comment]
Due to age of this issue (3 years) and no repeat problems similar to it, I think this can be closed.   However, @perilomo , if you are still affected by this or want to give a try again just to help us out (and you still are using Adblock), let us know and we can re-open.  

Possibly this was a result of not using https back then....?  In which case we should be all good now.
