### ISSUE TITLE
Resetting Password? 

### ISSUE THREAD

**Issue by MorrighuRaven** [naturalcrit/homebrewery#776]
So I feel like a dummy, but I cant find a place to reset my HomeBrewery password. Is there a link you can provide so I can reset my login information and whatnot? 

- Faith

**Comment by AlexeySachkov** [comment]
Hi, @MorrighuRaven 

Unfortunately this feature is not implemented. There is no way to reset your password because no information about you is stored on server (I mean something like email address, phone number, etc.)

I'm not sure that such changes even planned (see #412, #405, #375). But @stolksdorf proposed to integrate passport.js into the homebrewery (See [this comment](https://github.com/stolksdorf/homebrewery/issues/627#issuecomment-370257776) in #627):
> An actual account system! Using Passport.js to allow users to login using google, fb, github, etc. 

Integration with external services (Google, Facebook, etc.) will probably help solve "forgotten password" problem in the future.

**Comment by AlexeySachkov** [comment]
@calculuschild, I think that we can close this issue: any sensitive information (like email) will unlikely be ever stored by us and with Google integration available, "forgot password" issue should be less painful for our users. What do you think?

**Comment by calculuschild** [comment]
Closing. Google Drive integration is already implemented.
