### ISSUE TITLE
The top of Y and K get cut off when you start the title with # TEXT

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#848]
When the first letter after a `# Header` is a "Y" or "K", the top part gets cut off. 

See here: https://snag.gy/9pNrcT.jpg

Originally posted on the subreddit: https://www.reddit.com/r/homebrewery/comments/bex7p3/the_top_of_y_and_k_get_cut_off_when_you_start_the/

**Comment by ericscheid** [comment]
The issue is that some characters are taller than the line-height of the paragraph bounding-box and thus extrude beyond, and thus get clipped.

The solution, until the devs fix the stylesheet for the site, is to insert into your page content the following:

    <style>
      .phb h1+p {
        padding-top: 2em;
        margin-top: -2em;
        }
    </style>

That adds padding across the top of the paragraph, pushing the content down, and then shifts the entire paragraph upwards by the same amount.

**Comment by calculuschild** [comment]
This fix is probably fine. I just want to make sure it doesn't mess up any other positioning first.

**Comment by ericscheid** [comment]
It does seem to mess up a page that has two H1s. No idea why. Testing in Safari is even worse - the first paragraph is duplicated above the page content.

**Comment by ericscheid** [comment]
Saw a different bug to do with an initial dropcap descender appearing much separated from the full sigil due to an interposing image inserted after that paragraph. If you follow.

Bottom line .. there are browser bugs in play here. Weird obscure browser bugs.

**Comment by Gazook89** [comment]
I'm not sure this is an issue anymore?  Tested it and not getting the same result.  However, I do see that K, J, and F all extend to the right of their "frame" and can cover the text next to it.  I assume this is basically a font issue, and not even necessarily one that needs to be fixed since it is likely only an issue that comes up when using it in a drop-cap situation.

Using Chrome.

**Comment by calculuschild** [comment]
I don't see the cutoff issue either, but I do notice the K overlapping the title above as well. In addition, the spacing after a `# TITLE` seems to be a bit off. We can try to tidy up the spacings with the new renderer.
