### ISSUE TITLE
Editor highlighting for Markdown italics do not match rendered brew

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#852]
[Here](https://www.reddit.com/r/homebrewery/comments/d36mbo/issue_describe_your_issue_here/) is the original post on reddit.

> When a markdown element is positioned at the beginning of text, the text is highlighted with the meaning of that element. This is true even if the element is a closing element
>
> An example can be seen on the default Homebrewery at line 7, there is no space between the ** and "Simply..." which highlights the rest of the line in bold font, even though the bold only applies to "Try it!"
>
> https://i.redd.it/pmz687lzg5m31.png

**Comment by ericscheid** [comment]
Is this a bug in markdown, or a bug in whatever is used to style and format the brew code (which is markdown code)? This appears in the editing pane, but everything is OK in the display pane.

The bug seems to be triggered by the space in front of the terminating bold marker, not the space-or-lack after it.

This brew code:
```
1. **line starts with bold-marker but has no end marker
2. **marked for bolding** usual proper coding
3. **marked for bolding**no space here
4. **marked for bolding **misplaced space
5. **marked for bolding ** space either side of end-bolder
```
Looks like this in the editor:

1. **\*\*line starts with bold-marker but has no end marker**
2. **\*\*marked for bolding\*\* usual proper coding**
3. **\*\*marked for bolding\*\***no space here
4. **\*\*marked for bolding \*\*misplaced space**
5. **\*\*marked for bolding \*\* space either side of end-bolder**

Same thing happens with _\*italics\*_

Looks like a problem with the `codemirror` lib.

**Comment by calculuschild** [comment]
codemirror may very well have some updates that fix this problem. I know a lot of packages have fallen out of date and it might be time to start going through those and making sure updating those isn't going to break stuff.

**Comment by calculuschild** [comment]
I submitted a bug report to Codemirror. This is indeed on their side.

**Comment by ericscheid** [comment]
The was a recent bump of codemirror, and now the test cases above are slightly improved but not fixed.

**Comment by calculuschild** [comment]
Link to the bug report I submitted https://github.com/codemirror/CodeMirror/issues/6264

Seems like this particular behavior is actually correct according to the Markdown specs. It is actually our out-of-date that is rendering invalid styling. Once we update the Marked.js library, this Markdown will actually stop working, which will help users create better, valid Markdown and lead to fewer syntax errors and weird formatting issues.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
